var TREE_ITEMS = [
	['Home Page', 'admin.php',
		['Change Password', 'change_pass.php'],
		['FAQ section', '#',
			['Add New FAQ', 'add_faq.php'],
			['Modify a FAQ', 'modify_faq.php'],
			['Delete FAQs', 'remove_faq.php'],
		],
		['NEWS section', '#',
			['Add New NEWS', 'add_news.php'],
			['Modify a NEWS', 'modify_news.php'],
			['Delete NEWS', 'remove_news.php'],
		],
		['Manage Category', '#',
			['Add a category', 'add_category.php'],
			['Modify a category', 'modify_category.php'],
			['Delete categories', 'delete_category.php'],
		],
		['Manage Products', '#',
			['Add New Product', 'add_product.php'],
			['Modify a product', 'modify_product.php'],
			['Delete Products', 'remove_products.php'],
		],
		['Manage Antiques', '#',
			['Add New Antique', 'add_antique.php'],
			['Modify an Antique', 'modify_antique.php'],
			['Delete Antiques', 'remove_antiques.php'],
		],
		['<strong><font color=red>Log Out</font></strong>', 'logout.php'],
	]
];